name: 构建生成Spider Jar Gen CI

on:
 workflow_dispatch:
    inputs:
      SyncGitee:
        description: '是否同步Gitee仓库'
        required: false
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 必须：发布 Release 权限

    steps:
      #- name: Checkout current repo
      #  uses: actions/checkout@v4

      # 1. 拉取 Gitee TVSpider
      - name: Clone TVSpider from Gitee
        run: git clone -b spider_cyh --single-branch https://gitee.com/cyh92/TVSpider.git

      # 2. 设置 JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'jetbrains'
          cache: gradle

      # 构建 APK + Jar
      - name: Build with Gradle
        run: |
          cd TVSpider
          chmod +x gradlew
          ./gradlew app:assembleRelease

      # 给 sh 授权 + 执行 genJar.sh（核心！）
      - name: Run genJar.sh
        run: |
          cd TVSpider
          chmod +x ./jar/genJar.sh  # 必须加执行权限
          ./jar/genJar.sh           # 执行脚本

      - name: Set release datetime
        id: datetime
        run: |
          echo "datetime=$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S')" >> "$GITHUB_OUTPUT"

      # 发布 Release，名称带时间
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: auto-build-${{ github.sha }}
          name: "自动构建 Jar - ${{ steps.datetime.outputs.datetime }}"
          body: 由 GitHub Actions 自动构建
          files: |
            TVSpider/jar/*.jar
            TVSpider/jar/*.md5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: 同步更新
        if: success() && github.event.inputs.SyncGitee == 'true'
        run: |
           git clone https://cyh92:${{ secrets.MY_GITEE_TOKEN }}@gitee.com/cyh92/mybox.git
           ls
           find TVSpider/jar -maxdepth 1 -type f -name "*.jar" -exec cp -f {} mybox/jar/ \;
           
           cd mybox
           git config user.name "cyh92"
           git config user.email "cyh92@live.cn"
           git add .
           # 判断是否有变更，无变更就跳过提交推送
            if git diff --cached --quiet;then
              echo "没有文件变更，跳过提交"
            else
              git commit -m "更新jar包 $(date '+%Y-%m-%d %H:%M:%S')"
              git push
            fi
