name: Build & Release All Release AAR

# ======================= 【可配置变量】 =======================
env:
  REPO: FongMi/media
  BRANCH: main
# ==============================================================

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REPO }}
          ref: ${{ env.BRANCH }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build all Release AAR
        run: ./gradlew assembleRelease

      # 关键：自动收集 media/libraries 下 任意层级 的所有 *release.aar
      - name: Collect all release AAR files
        run: |
          mkdir -p release_aars
          find media/libraries -name "*release.aar" -type f -exec cp {} release_aars/ \;

      - name: Create Release and Upload ALL AAR
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ github.run_number }}
          name: Release AAR ${{ github.run_number }}
          files: release_aars/*.aar
