# This is a basic workflow to help you get started with Actions

name: 构建筱筱阅读mini版

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs: 
      defaultUrl:
        description: '使用仓库'
        required: true
        default: 'https://gitee.com/cyh92/legado.git'  
        type: choice
        options:
          - https://gitee.com/cyh92/legado.git
          - https://github.com/cyh92/legado.git
      defaultBranch:
        description: '使用分支'
        required: true
        default: 'new-dev'     
      publishGitee:
        description: '是否同步发布到 Gitee Release'
        required: false
        type: boolean
        default: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: 拉取构建脚本
        uses: actions/checkout@v4
      - name: 克隆 Gitee 代码
        run: |
          git clone -b ${{ github.event.inputs.defaultBranch }} ${{ github.event.inputs.defaultUrl }} legado

      - name: 安装 JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: 复制签名文件
        run: |    
          cp -f sign/legado.jks legado/app/legado.jks    
          sed '$r '"$GITHUB_WORKSPACE/.github/legado/legado.sign"'' $GITHUB_WORKSPACE/legado/gradle.properties -i
          sed -i "s/^\s*alias libs.plugins.google.services/\/\/&/" $GITHUB_WORKSPACE/legado/app/build.gradle
          cd legado/app
          ls

      - name: 生成版本号
        id: date
        run: |
          # 拼接版本前缀+上海时区年月日时分：格式示例 3.26072515
          version="3.$(TZ=Asia/Shanghai date +%y%m%d%H)"
          # 标准写法输出变量到 GitHub Actions 上下文
          echo "version=$version" >> "$GITHUB_OUTPUT"
          # 打印当前生成的版本号
          echo "当前版本号: $version"
          sed -i "s/^def version = .*/def version = \"$version\"/" "$GITHUB_WORKSPACE/legado/app/build.gradle"
          cat $GITHUB_WORKSPACE/legado/app/build.gradle
          
      - name: 执行自定义注入脚本
        env:
          APP_WORKSPACE: ${{ github.workspace }}/legado
          APP_LAUNCH_NAME: "筱筱自读"
          SECRETS_RENAME: "true"
        run: |
          ls
          chmod +x diy/legado_custom.sh
          diy/legado_custom.sh

      - name: 构建 Release APK
        working-directory: ./legado
        run: |
         chmod +x gradlew
         ./gradlew assembleApprelease -ParmOnly=true --build-cache --parallel --daemon --warning-mode all

        # 1. 创建 apks 文件夹
      - name: 创建 apks 文件夹
        run: mkdir -p apks

      # 2. 复制所有 release apk 到 apks 目录
      - name: 复制所有 APK 到 apks 目录
        run: |
          # find legado/app/build/outputs/apk -name "*.apk" | grep -v debug | xargs -I {} cp {} apks/
          # 生成文件名
          bash .github/legado/scripts/collect-apks.sh \
            $GITHUB_WORKSPACE/legado/app/build/outputs/apk \
            $GITHUB_WORKSPACE/apks \
            app \
            ${{ steps.date.outputs.version }} \
            "" \
            arm

      # 3. 读取 apks 目录下所有文件
      - name: 获取所有 APK
        id: apk
        run: echo "files=apks/*" >> $GITHUB_OUTPUT

      - name: Prepare Release Notes
        run: |
          bash .github/legado/extract-latest-update.sh \
            $GITHUB_WORKSPACE/legado/app/src/main/assets/updateLog.md \
            > "$GITHUB_WORKSPACE/legado/release-notes.md"

          cat $GITHUB_WORKSPACE/legado/release-notes.md
          
      - name: 自动发布 Release
        if: success()
        uses:  softprops/action-gh-release@v1
        with:
          name: legado_app_${{ steps.date.outputs.version }}
          tag_name: ${{ steps.date.outputs.version }}
          body_path: ${{ github.workspace }}/legado/release-notes.md
          draft: false
          prerelease: false
          files: ${{ steps.apk.outputs.files }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ========== 发布Gitee Release（使用MY_GITEE_TOKEN） ==========
      - name: 同步Tag并发布Gitee Release
        if: success() && github.event.inputs.publishGitee == 'true'
        env:
          MY_GITEE_TOKEN: ${{ secrets.MY_GITEE_TOKEN }}
          GITEE_REPO: cyh92/legado
          TAG_NAME: ${{ steps.date.outputs.version }}
          RELEASE_TITLE: legado_app_${{ steps.date.outputs.version }}
          APK_DIR: ${{ github.workspace }}/apks
          TARGET_BRANCH: ${{ github.event.inputs.defaultBranch }}
        run: |
          # 2. 创建Gitee Release
          NOTE_FILE="${{ github.workspace }}/legado/release-notes.md"
          if [[ ! -f "$NOTE_FILE" ]]; then
            echo "ERROR: 发布日志文件不存在 $NOTE_FILE"
            exit 1
          fi
          # 读取日志并转义双引号
          RELEASE_NOTE_CONTENT=$(cat "$NOTE_FILE" | sed 's/"/\\"/g')
          # apks的文件列表
          ls ${{ steps.apk.outputs.files }}
          # APK_DIR的文件列表
          ls ${APK_DIR}
          API_URL="https://gitee.com/api/v5/repos/cyh92/legado/releases"
          BODY="自动构建发布版本 ${TAG_NAME}
          构建分支：${TARGET_BRANCH}
          ${RELEASE_NOTE_CONTENT}"
          
          #CREATE_RES=$(curl -X POST --header 'Content-Type: application/json;charset=UTF-8' '${API_URL}' -d '{"access_token":"${{ secrets.MY_GITEE_TOKEN }}","tag_name":"${TAG_NAME}","name":"${RELEASE_TITLE}","body":"${BODY}","target_commitish":"${TARGET_BRANCH}"}')
          CREATE_RES=$(curl -X POST -H "Content-Type: application/json;charset=UTF-8" "${API_URL}" -d "{\"access_token\":\"${{ secrets.MY_GITEE_TOKEN }}\",\"tag_name\":\"${TAG_NAME}\",\"name\":\"${RELEASE_TITLE}\",\"body\":\"${BODY}\",\"target_commitish\":\"${TARGET_BRANCH}\"}")
          # 提取release id
          RELEASE_ID=$(echo "$CREATE_RES" | jq -r '.id')
          if [[ "$RELEASE_ID" == "null" || -z "$RELEASE_ID" ]]; then
            echo "创建Gitee Release失败，返回：$CREATE_RES"
            exit 1
          fi
          echo "Gitee Release 创建成功 ID: $RELEASE_ID"

          # 3. 上传所有APK附件
          for apk in ${APK_DIR}/*.apk; do
            if [ -f "$apk" ]; then
              echo "正在上传附件: $apk"             
              curl -s -X POST \
              -F "access_token=${MY_GITEE_TOKEN}" \
              -F "owner=cyh92" \
              -F "repo=legado" \
              -F "release_id=${RELEASE_ID}" \
              -F "file=@$apk" \
              "$API_URL/${RELEASE_ID}/attach_files"
            echo "上传完成：$apk"
            fi
          done
          echo "所有APK附件上传完成"
